In [1]:
import imp
import swising as sw


In [220]:
import numpy as np

In [146]:
wor

NameError: name 'wor' is not defined

In [147]:
11//4

2

In [148]:
11 -2*4

3

In [5]:
imp.reload(sw)
w = sw.World(400,400,1/2.27)
w.swupdate()
w.spinlattice()

array([[ 1,  1,  1, ...,  1,  1, -1],
       [ 1,  1,  1, ...,  1,  1,  1],
       [ 1,  1,  1, ...,  1,  1,  1],
       ...,
       [ 1,  1,  1, ...,  1,  1,  1],
       [ 1,  1,  1, ...,  1,  1,  1],
       [ 1,  1,  1, ...,  1,  1,  1]])

In [201]:
w.spins.sum()

16

In [8]:
import math
w.padd = 1- math.exp(-2/2.269  )

array([ 1, -1,  1,  1,  1,  1, -1, -1, -1, -1,  1, -1, -1, -1,  1, -1])

In [61]:
sw.index2coord(3, 4,4)

array([0, 3])

In [65]:
sw.coord2index([-1,0],4,4)

12

In [70]:
for i in np.ones(12):
    if not i:
        print("a")

In [71]:
1 if 1==0 else 2

2

In [73]:
l=[1,2]

In [74]:
l.pop()

2

In [75]:
l

[1]

In [80]:
if not 1==3 and  2==2:
    print(2)

2


In [4]:
%gui qt

from pyqtgraph.Qt import QtCore, QtGui
import numpy as np
import pyqtgraph as pg
import pyqtgraph.ptime as ptime
import time

app = QtGui.QApplication([])

## Create window with GraphicsView widget
win = pg.GraphicsLayoutWidget()
win.show()  ## show widget alone in its own window
win.setWindowTitle('pyqtgraph example: ImageItem')
view = win.addViewBox()

## lock the aspect ratio so pixels are always square
view.setAspectLocked(True)


## Create image item
img = pg.ImageItem(border='w', levels=[-1,1])

view.addItem(img)

## Create random image
data = w.spinlattice()



def updateData():
    global img, data


    w.swupdate()
    data = w.spinlattice()
    
    img.setImage(data)
    img.setLevels([-1,1])
   
    QtCore.QTimer.singleShot(1, updateData)
    
    time.sleep(0.1)
    #print "%0.1f fps" % fps
    

updateData()